import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/navbar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pizza Don Mario",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="icons/pizza.png"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <img
            className="logo"
            src="/images/pizza-mario-logo.png"
            alt="Pizzas Don Mario"
          />
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <p>&copy; 2021 Pizzas Don Mario</p>
        </footer>
      </body>
    </html>
  );
}
